import sharp from "sharp";
import { readdir, mkdir, writeFile } from "node:fs/promises";
const directory = "public/images/gallery";
await mkdir(`${directory}/responsive`, { recursive: true });
const names = (await readdir(directory))
  .filter((name) => name.endsWith(".webp") && !name.startsWith("video-"))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
const dimensions = {};
for (const name of names) {
  const image = sharp(`${directory}/${name}`);
  const { width, height } = await image.metadata();
  dimensions[name.replace(".webp", "")] = { width, height };
  if (width > 800) {
    for (const size of [480, 800])
      await image
        .clone()
        .resize({ width: size, withoutEnlargement: true })
        .webp({ quality: 78 })
        .toFile(
          `${directory}/responsive/${name.replace(".webp", `-${size}.webp`)}`,
        );
  }
}
await writeFile(
  "src/data/galleryDimensions.ts",
  `// Generated by scripts/optimize-gallery.mjs from the supplied originals.\nexport const galleryDimensions: Record<string, {width:number; height:number}> = ${JSON.stringify(dimensions, null, 2)};\n`,
);
console.log(
  `Optimized ${names.length} gallery photos; original files preserved.`,
);
