import sharp from "sharp";
import { readdir, mkdir, writeFile, access } from "node:fs/promises";
const directory = "public/images/gallery";
await mkdir(`${directory}/responsive`, { recursive: true });
// Keep the uploaded PNG originals and produce smaller web assets separately.
const uploadedDirectory = "public/images/Farmnatura upscaled Images";
for (let index = 1; index <= 5; index++) {
  const source = `${uploadedDirectory}/Image ${index}.png`;
  try {
    await access(source);
  } catch {
    continue;
  }
  await sharp(source)
    .autoOrient()
    .webp({ quality: 86, effort: 5 })
    .toFile(`${directory}/farmnatura-upscaled-${index}.webp`);
}
const names = (await readdir(directory))
  .filter((name) => name.endsWith(".webp") && !name.startsWith("video-"))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
const dimensions = {};
for (const name of names) {
  const image = sharp(`${directory}/${name}`);
  const { width, height } = await image.metadata();
  dimensions[name.replace(".webp", "")] = { width, height };
  if (width > 800) {
    for (const size of [480, 800])
      await image
        .clone()
        .resize({ width: size, withoutEnlargement: true })
        .webp({ quality: 78 })
        .toFile(
          `${directory}/responsive/${name.replace(".webp", `-${size}.webp`)}`,
        );
  }
}
await writeFile(
  "src/data/galleryDimensions.ts",
  `// Generated by scripts/optimize-gallery.mjs from the supplied originals.\nexport const galleryDimensions: Record<string, {width:number; height:number}> = ${JSON.stringify(dimensions, null, 2)};\n`,
);
console.log(
  `Optimized ${names.length} gallery photos; original files preserved.`,
);
