import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Leaf, Sprout, Flower2, Bird, Bug, Trees, Wheat, X, Menu, Plus, Minus } from 'lucide-react';
import { FarmerScene, FarmPanorama, Bee, FeatureArt } from './components/Illustrations';
import ContactDialog from './components/ContactDialog';
import { experiences, faqs, contact } from './data/content';
import { useAnimations } from './hooks/useAnimations';
const creatures=[{name:'Living soil',sub:'It all starts here',Icon:Sprout},{name:'Native seeds',sub:'Rooted in our land',Icon:Wheat},{name:'Fruit trees',sub:'A sweeter season',Icon:Trees},{name:'Pollinators',sub:'Little farm helpers',Icon:Bug},{name:'Birdlife',sub:'Our morning chorus',Icon:Bird},{name:'Wildflowers',sub:'Room to grow wild',Icon:Flower2}];
function Wave({color,flip=false}:{color:string;flip?:boolean}){return <svg className={`wave ${flip?'wave-flip':''}`} viewBox="0 0 1440 100" preserveAspectRatio="none" aria-hidden="true"><path d="M0 56C245 126 477 93 713 46C973-6 1210-8 1440 56V100H0Z" fill={color}/></svg>}
export default function App(){
 const [menu,setMenu]=useState(false),[visit,setVisit]=useState(false),[detail,setDetail]=useState<string|null>(null),[active,setActive]=useState(0),[faq,setFaq]=useState<number|null>(null);
 useAnimations();
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);setDetail(null);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 const openVisit=()=>{setMenu(false);setVisit(true);};
 return <><header className="site-header"><a className="wordmark" href="#home" aria-label="Farm Natura home"><span>farm natura<Leaf size={19}/></span></a><nav aria-label="Main navigation" className={menu?'is-open':''}><a href="#farm-life" onClick={()=>setMenu(false)}>Farm life</a><a href="#experiences" onClick={()=>setMenu(false)}>Experiences</a><a href="#our-approach" onClick={()=>setMenu(false)}>Our approach</a><button className="button" onClick={openVisit}>Come, walk the land <ArrowUpRight size={17}/></button></nav><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main><section id="home" className="hero"><div className="hero-inner"><div className="hero-art"><div className="estate-label"><span className="estate-seal"><Sprout size={30}/></span><span>NATURAL FARMING<br/>A WAY OF LIFE</span></div><FarmerScene/></div><div className="hero-copy"><h1>Growing a Life<br/>Rooted in Nature</h1><p>Somewhere between the soil and the sky,<br className="desktop-break"/> there’s a life waiting to be lived. Discover<br className="desktop-break"/> Farm Natura — a natural farming estate<br className="desktop-break"/> near Hyderabad, where your family can<br className="desktop-break"/> grow, belong, and simply breathe.</p></div></div><svg className="flight-path" viewBox="0 0 1440 900" preserveAspectRatio="none" aria-hidden="true"><path id="bee-path" d="M520 -10C830 90 490 310 782 295S1190 190 1310 435 1280 690 1450 650" fill="none" stroke="#87906c" strokeDasharray="4 6" strokeWidth="1"/></svg><Bee className="hero-bee"/><a className="scroll-hint" href="#farm-life">A slower life starts here <ArrowDown size={18}/></a><Wave color="#ecedd4"/></section>
 <section id="farm-life" className="intro pale"><div className="container"><div className="editorial-row"><div className="editorial-copy" data-reveal><h2>A Little More Earth.<br/>A Little More Life.</h2><p>Trade the everyday rush for the rhythm of the seasons. Own a piece of land, grow food for your family, and find your way back to what matters.</p><p>At Farm Natura, natural farming and family life grow together.</p></div><div className="organic-photo" data-reveal><img src="/images/farm.jpg" alt="Green cultivated land and trees at Farm Natura" loading="lazy"/></div></div><div className="editorial-row reversed"><div className="organic-photo alternate" data-reveal><img src="/images/goshala.jpg" alt="Cows in Farm Natura’s goshala" loading="lazy"/></div><div className="editorial-copy" data-reveal><h2>Good Living Starts<br/>With Living Soil.</h2><p>Care for the soil, and the soil cares for us. Our chemical-free farming practices make space for native seeds, seasonal crops, fruit-bearing trees, and the little lives that keep a farm thriving.</p><a className="text-link" href="#our-approach">Discover our approach <ArrowRight size={18}/></a></div></div><Bee className="scroll-bee"/><div className="biodiversity" data-reveal><h2>A Farm Full of Life</h2><div className="creature-list">{creatures.map(({name,sub,Icon})=><div key={name}><span className="creature-icon"><Icon strokeWidth={1.3}/></span><h3>{name}</h3><p>{sub}</p></div>)}</div></div></div></section>
 <section className="landscape" aria-label="Explore the illustrated Farm Natura landscape"><div className="landscape-top"><span>110+ acres. A thousand little moments.</span><span className="landscape-instruction">Scroll to explore <ArrowRight size={17}/></span></div><div className="landscape-track"><FarmPanorama/><div className="landscape-note note-one"><span className="number-dot">01</span><h3>From soil to soul.</h3><p>A farm that grows with you.</p></div><div className="landscape-note note-two"><span className="number-dot">02</span><h3>Room to put down roots.</h3><p>Your own little corner of nature.</p></div><div className="landscape-note note-three"><span className="number-dot">03</span><h3>Life, a little slower.</h3><p>Shared with the ones you love.</p></div></div></section>
 <section className="farm-gallery dark-section"><div className="container"><div className="section-heading" data-reveal><h2>This Is What Coming<br/>Home Feels Like.</h2><p>Real places. Real moments.<br/>A glimpse of life at Farm Natura.</p></div><div className="gallery-frame"><img key={active} src={['/images/farm.jpg','/images/farmhouse.jpg','/images/goshala.jpg','/images/dining.jpg'][active]} alt={['The lush Farm Natura estate','A farmhouse at Farm Natura','Farm Natura goshala','Dining at Farm Natura'][active]}/><div className="gallery-caption"><span>{['A landscape to call your own','A home away from the hurry','In good company','Together around the table'][active]}</span><span>0{active+1} / 04</span></div></div><div className="gallery-controls" aria-label="Gallery images">{['The land','The farmhouse','The goshala','Gathering'].map((label,i)=><button key={label} className={active===i?'active':''} onClick={()=>setActive(i)} aria-pressed={active===i}><span>0{i+1}</span>{label}</button>)}</div></div><Wave color="#fffff2"/></section>
 <section id="experiences" className="experiences cream"><div className="container"><h2 data-reveal>A Life With More Possibilities</h2><div className="experience-grid">{experiences.map(item=><article data-reveal key={item.id}><FeatureArt kind={item.kind}/><span className="eyebrow">{item.number} / FARM NATURA</span><h3>{item.title}</h3><p>{item.text}</p><div className="tags">{item.tags.map(tag=><span key={tag}><Leaf size={13}/>{tag}</span>)}</div><button className="text-link" onClick={()=>setDetail(item.id)}>Explore <ArrowRight size={17}/></button><div className="experience-detail" hidden={detail!==item.id}><p>{item.detail}</p><button className="text-link" onClick={openVisit}>Ask us about it <ArrowUpRight size={16}/></button><button className="detail-close" aria-label={`Close ${item.title} details`} onClick={()=>setDetail(null)}><X size={17}/></button></div></article>)}</div></div></section>
 <section id="our-approach" className="approach cream"><div className="narrow"><h2 data-reveal>Care for the Land.<br/>It’s in Our Nature.</h2><p className="section-intro" data-reveal>Indulge. Involve. Impact nature.<br/>A simple belief, rooted in everything we do.</p><div className="approach-cards"><article data-reveal><span className="round-icon"><Sprout/></span><h3>Rooted in natural farming</h3><p>Indigenous seeds, living soil and chemical-free practices. We work with the land and its natural rhythms to grow seasonal food.</p><a className="text-link" href="https://www.farmnatura.in/natural-farming" target="_blank" rel="noreferrer">Learn about natural farming <ArrowUpRight size={16}/></a></article><article data-reveal><span className="round-icon"><Trees/></span><h3>Cared for, together</h3><p>Your land, with everyday farming managed by a dedicated team. A community that gives families more time to enjoy the farm.</p><button className="text-link" onClick={openVisit}>Meet Farm Natura <ArrowRight size={16}/></button></article></div></div><Wave color="#ecedd4"/></section>
 <section id="visit" className="visit pale"><div className="narrow"><h2 data-reveal>Close Enough to Visit.<br/>Far Enough to Breathe.</h2><p className="section-intro" data-reveal>Find us in Kandukur, along the Srisailam Highway.<br/>A different pace of life, just outside Hyderabad.</p><div className="location-list" data-reveal>{[['Rajiv Gandhi International Airport','Approx. 25 minutes'],['Tukkuguda ORR exit','Approx. 20 minutes'],['Kandukur','Srisailam Highway corridor']].map(([name,time],i)=><a key={name} href="https://www.google.com/maps/search/?api=1&query=Farm+Natura+Kandukur" target="_blank" rel="noreferrer"><span className="number-dot">{i+1}</span><span>{name}</span><small>{time}</small><ArrowUpRight size={19}/></a>)}</div><p className="small-note">Travel times are approximate and depend on your route and traffic.</p><button className="button dark" onClick={openVisit}>Plan your farm visit <ArrowUpRight size={18}/></button></div><Wave color="#fffff2"/></section>
 <section className="faq cream"><div className="narrow"><h2 data-reveal>A Few Things You<br/>Might Be Wondering.</h2><div className="faq-list">{faqs.map(([q,a],i)=><div key={q}><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span>{faq===i?<Minus size={20}/>:<Plus size={20}/>}</button><div id={`faq-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></div><Wave color="#204116"/></section>
 <section className="closing dark-section"><div className="container"><span className="eyebrow" data-reveal>GROW FOOD. GROW HEALTH. GROW A LIFE.</span><h2 data-reveal>Your Next Chapter<br/>Could Be a Little Greener.</h2><p data-reveal>Come for a walk. Stay for the possibilities.</p><button className="button" onClick={openVisit}>Come, walk the land <ArrowUpRight size={18}/></button><div className="closing-sprout"><FeatureArt kind="orchard"/></div></div></section></main>
 <footer className="dark-section"><div className="container"><div className="footer-main"><a className="wordmark" href="#home"><span>farm natura<Leaf size={22}/></span><small>BY PLANET GREEN</small></a><p>{contact.address}</p><div><a href={`tel:${contact.tel}`}>{contact.phone} <ArrowUpRight size={16}/></a><a href="https://www.farmnatura.in/" target="_blank" rel="noreferrer">farmnatura.in <ArrowUpRight size={16}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Farm Natura</span><span>A life rooted in nature.</span><a href="#home">Back to the sky ↑</a></div></div></footer><ContactDialog open={visit} onClose={()=>setVisit(false)}/></>;
}
