// Generated by scripts/optimize-gallery.mjs from the supplied originals.
export const galleryDimensions: Record<
  string,
  { width: number; height: number }
> = {
  dining: {
    width: 487,
    height: 480,
  },
  farm: {
    width: 487,
    height: 480,
  },
  farmhouse: {
    width: 487,
    height: 480,
  },
  farmhouse2: {
    width: 487,
    height: 480,
  },
  "farmnatura-upscaled-1": {
    width: 1254,
    height: 1254,
  },
  "farmnatura-upscaled-2": {
    width: 1254,
    height: 1254,
  },
  "farmnatura-upscaled-3": {
    width: 1254,
    height: 1254,
  },
  "farmnatura-upscaled-4": {
    width: 1254,
    height: 1254,
  },
  "farmnatura-upscaled-5": {
    width: 1254,
    height: 1254,
  },
  fnsi1: {
    width: 1280,
    height: 853,
  },
  fnsi2: {
    width: 1600,
    height: 720,
  },
  fnsi3: {
    width: 1600,
    height: 720,
  },
  fnsi4: {
    width: 1600,
    height: 900,
  },
  fnsi5: {
    width: 1600,
    height: 1067,
  },
  fnsi6: {
    width: 1600,
    height: 900,
  },
  fnsi7: {
    width: 963,
    height: 1280,
  },
  fnsi8: {
    width: 1280,
    height: 853,
  },
  fnsi9: {
    width: 1080,
    height: 713,
  },
  fnsi10: {
    width: 1280,
    height: 821,
  },
  fnsi11: {
    width: 1280,
    height: 853,
  },
  fnsi12: {
    width: 1600,
    height: 900,
  },
  fnsi13: {
    width: 1600,
    height: 1067,
  },
  fnsi14: {
    width: 1600,
    height: 1067,
  },
  fnsi15: {
    width: 1600,
    height: 1067,
  },
  fnsi16: {
    width: 1600,
    height: 1067,
  },
  fnsi17: {
    width: 1600,
    height: 1067,
  },
  fnsi18: {
    width: 1600,
    height: 1067,
  },
  fnsi19: {
    width: 1600,
    height: 1067,
  },
  fnsi20: {
    width: 1600,
    height: 1067,
  },
  fnsi21: {
    width: 1600,
    height: 900,
  },
  goshala: {
    width: 1254,
    height: 1254,
  },
  goshalatopview: {
    width: 1254,
    height: 1254,
  },
  openfarm: {
    width: 1254,
    height: 1254,
  },
  openplace2: {
    width: 1254,
    height: 1254,
  },
};
